### ISSUE TITLE
关于27/4

### ISSUE THREAD

**Issue by singlecha** [shaqsnake/Data-Structures-and-Algorithms-in-Python#1]
![image](https://user-images.githubusercontent.com/11693424/49922499-d6d73d80-feeb-11e8-98b4-8dd1baad2b7a.png)
27/4结果是否为6，两个都为整型的时候，结果似乎也应该会是整型
27/4.0为6.75

**Comment by shaqsnake** [comment]
python里的除法是通过重载**operator**里的*truediv*和*\_\_truediv\_\_*实现的。

![image](https://user-images.githubusercontent.com/1336914/49995456-29395c80-ffc7-11e8-9bd1-7e3298214b71.png)
上图是官方的文档的解释里也举例说明了两个整数相除的结果应该和我们现实中“真正”的除法结果是一致的，这点和C语言有所不同。

详见 [python3 operator 文档](https://docs.python.org/3/library/operator.html)
